services:

  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: alfresco
      POSTGRES_DB: alfresco
      PGUSER: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    volumes:
      - postgres-data:/var/lib/postgresql/data

  activemq:
    image: docker.io/alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "--user", "admin:${ACTIVEMQ_ADMIN_PASSWORD}", "http://localhost:8161/admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    volumes:
      - activemq-data:/opt/activemq/data

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_TAG}
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5 
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
        reservations:
          cpus: '1'
          memory: 1g
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:${ELASTICSEARCH_TAG}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy

  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:${SHARED_FILESTORE_TAG}
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          cpus: '0.25'
          memory: 256m      
    volumes:
      - shared-file-store-data:/tmp/Alfresco/sfs        

  transform-core-aio:
    image: docker.io/alfresco/alfresco-transform-core-aio:${TRANSFORM_TAG}
    environment:
      ACTIVEMQ_URL: nio://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
      FILE_STORE_URL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
        reservations:
          cpus: '1'
          memory: 1g
    depends_on: 
      activemq:
        condition: service_healthy
      shared-file-store:
        condition: service_healthy

  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:${TRANSFORM_ROUTER_TAG}
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      ACTIVEMQ_URL: nio://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
      CORE_AIO_URL: http://transform-core-aio:8090
      FILE_STORE_URL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    depends_on: 
      activemq:
        condition: service_healthy
      transform-core-aio:
        condition: service_healthy

  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:${REPO_TAG}
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=${METADATA_KEYSTORE_PASSWORD}
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=${METADATA_KEYSTORE_METADATA_PASSWORD}
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dindex.subsystem.name=elasticsearch
        -Delasticsearch.createIndexIfNotExists=true
        -Delasticsearch.host=elasticsearch
        -Delasticsearch.port=9200
        -Dcsrf.filter.enabled=false
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Dmessaging.broker.username=admin
        -Dmessaging.broker.password=${ACTIVEMQ_ADMIN_PASSWORD}       
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Ddsync.service.uris=http://localhost:9090/alfresco
        -Ddeployment.method=DOCKER_COMPOSE
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3gb
        reservations:
          cpus: '1'
          memory: 2gb
    depends_on: 
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
      transform-router:
        condition: service_healthy
    volumes:
      - alf-repo-data:/usr/local/tomcat/alf_data

  search-reindexing:
    image: quay.io/alfresco/alfresco-elasticsearch-reindexing:${ESC_TAG}
    environment:
      ALFRESCO_ACCEPTED_CONTENT_MEDIA_TYPES_CACHE_BASE_URL: >-
        http://transform-core-aio:8090/transform/config
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      SPRING_ACTIVEMQ_USERNAME: admin
      SPRING_ACTIVEMQ_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      SPRING_DATASOURCE_USERNAME: alfresco
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      transform-router:
        condition: service_healthy
      alfresco:
        condition: service_healthy

  search:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing:${ESC_TAG}
    environment:
      ALFRESCO_ACCEPTED_CONTENT_MEDIA_TYPES_CACHE_BASE_URL: >-
        http://transform-core-aio:8090/transform/config
      ALFRESCO_SHAREDFILESTORE_BASEURL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      SPRING_ACTIVEMQ_USERNAME: admin
      SPRING_ACTIVEMQ_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
        reservations:
          cpus: '1'
          memory: 1g
    depends_on:
      search-reindexing: 
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
      activemq:
        condition: service_healthy

  sync-service:
    image: quay.io/alfresco/service-sync:${SYNC_SERVICE_TAG}
    environment:
      JAVA_OPTS: >-
        -Dsql.db.driver=org.postgresql.Driver
        -Dsql.db.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsql.db.username=alfresco
        -Dsql.db.password=${POSTGRES_PASSWORD}
        -Dmessaging.broker.host=activemq
        -Dmessaging.username=admin
        -Dmessaging.password=${ACTIVEMQ_ADMIN_PASSWORD}
        -Drepo.hostname=alfresco
        -Drepo.port=8080
        -Ddw.server.applicationConnectors[0].type=http
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
      alfresco:
        condition: service_healthy        
    ports:
      - "9090:9090"

  share:
    image: docker.io/alfresco/alfresco-share:${SHARE_TAG}
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    depends_on: 
      alfresco:
        condition: service_healthy

  digital-workspace:
    image: quay.io/alfresco/alfresco-digital-workspace:${DIGITAL_WORKSPACE_TAG}
    environment:
      APP_CONFIG_PROVIDER: "ECM"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      BASE_PATH: ./
      APP_CONFIG_PLUGIN_PROCESS_SERVICE: "false"
      APP_CONFIG_PLUGIN_MICROSOFT_ONLINE: "false"
      APP_BASE_SHARE_URL: "http://localhost:8080/workspace/#/preview/s"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          cpus: '0.25'
          memory: 256m
    depends_on: 
      alfresco:
        condition: service_healthy

  control-center:
    image: quay.io/alfresco/alfresco-control-center:${CONTROL_CENTER_TAG}
    environment:
      APP_CONFIG_PROVIDER: "ECM"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      BASE_PATH: ./
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          cpus: '0.25'
          memory: 256m
    depends_on: 
      alfresco:
        condition: service_healthy

  proxy:
    image: docker.io/alfresco/alfresco-acs-nginx:${NGINX_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          cpus: '0.25'
          memory: 256m
    depends_on:
      share:
        condition: service_started
      digital-workspace:
        condition: service_started
      control-center:
        condition: service_started
      sync-service:
        condition: service_started
    ports:
      - "8080:8080"

volumes:
  activemq-data:
  postgres-data:
  shared-file-store-data:
    driver_opts:
      type: tmpfs
      device: tmpfs    
  es-data:
  alf-repo-data:
  solr-data: